name: cassa_v19
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  esc_pos_utils_plus: ^2.0.4
  flutter_pos_printer_platform_image_3: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png